version: '3'
services:
  application:
    build:
      context: '.'
      dockerfile: 'src/main/docker/Dockerfile'
    ports:
      - '8080:8080'
    environment:
      DATABASE_HOSTNAME: $DATABASE_HOSTNAME
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
  database:
    image: 'postgres:16.2-bookworm'
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql/data'
volumes:
  database:
    external: false
